image: gradle:jdk-11

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradew assemble

test:
  stage: test
  script:
    - ./gradlew check



