/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;

import org.json.JSONObject;
import src.exceptions.InvalidGameDescriptionException;
import src.gameEngine.GameEngine;
import src.parser.GameDesc;
import src.parser.Parser;
import src.player.LocalPlayer;
import src.player.Player;

public class main {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws InvalidGameDescriptionException {
//        System.out.println(new main().getGreeting());
        Parser parser = new Parser();
        JSONObject GameJSON = Parser.readJSONFile(args[0]);
        GameDesc gameDesc = parser.parseGameDescription(GameJSON);
//        System.out.println(gameDesc);
        Player[] playerArray = {new LocalPlayer(0), new LocalPlayer(1), new LocalPlayer(2), new LocalPlayer(3)};
        GameEngine.main(gameDesc, 0, playerArray);
    }
}
